server:
  port: 7071
spring:
  application:
    name: server-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}